/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.reserva_controlador;
import hotel.conexion;
import javax.swing.JOptionPane;
import modelo.reserva;
import java.awt.FlowLayout;
import java.text.DecimalFormat;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cristian
 */
public class control_reserva extends javax.swing.JFrame {

    
    reserva_controlador hc =new reserva_controlador();
    reserva nueva_reserva = new reserva();
    conexion cc = new conexion();
    Connection con = cc.getConnection();
    PreparedStatement ps;
    ResultSet rs;
    private menu principal;
    /**
     * Creates new form control_reserva
     */
    
    public void ComboBoxmoneda() {
        cmb_forma_pago.addItem("Dolar");
        cmb_forma_pago.addItem("Euro");
        cmb_forma_pago.addItem("libra");
        cmb_forma_pago.addItem("Yen");
        cmb_forma_pago.addItem("won");
    }
    
    public control_reserva(menu p) {
        initComponents();
        principal=p;
        ComboBoxmoneda();
        spin_num.setModel(new SpinnerNumberModel(1, 1, null, 1)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        bot_buscar = new javax.swing.JButton();
        bot_volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datos = new javax.swing.JTable();
        bot_limpiar = new javax.swing.JButton();
        bot_editar = new javax.swing.JButton();
        bot_eliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_id_huesped = new javax.swing.JLabel();
        txt_fecha_entrada = new javax.swing.JTextField();
        txt_fecha_salida = new javax.swing.JTextField();
        txt_valor = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        cmb_forma_pago = new javax.swing.JComboBox<>();
        bot_actualizar = new javax.swing.JButton();
        bot_cancelar = new javax.swing.JButton();
        spin_num = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Control Reserva");

        jLabel2.setText("Buscar por el nombre de usuario:");

        bot_buscar.setText("Buscar");
        bot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarActionPerformed(evt);
            }
        });

        bot_volver.setText("volver");
        bot_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_volverActionPerformed(evt);
            }
        });

        tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_reserva", "fecha entrada", "fecha salida", "valor", "forma de pago", "id_huesped", "total"
            }
        ));
        jScrollPane1.setViewportView(tbl_datos);

        bot_limpiar.setText("LIMPIAR");
        bot_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiarActionPerformed(evt);
            }
        });

        bot_editar.setText("EDITAR");
        bot_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_editarActionPerformed(evt);
            }
        });

        bot_eliminar.setText("ELIMINAR");
        bot_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_eliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha entrada:");

        jLabel4.setText("Fecha Salida:");

        jLabel5.setText("Valor en dolar:");

        jLabel6.setText("Forma de Pago:");

        jLabel7.setText("Total (moneda de tu pais):");

        txt_fecha_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecha_salidaActionPerformed(evt);
            }
        });

        cmb_forma_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_forma_pagoActionPerformed(evt);
            }
        });

        bot_actualizar.setText("Actualizar");
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });

        bot_cancelar.setText("Cancelar");
        bot_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cancelarActionPerformed(evt);
            }
        });

        spin_num.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_numStateChanged(evt);
            }
        });

        jLabel8.setText("dias:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Actualizacion de datos");

        txt_id.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lbl_id_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spin_num, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_fecha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_forma_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(208, 208, 208)
                                .addComponent(bot_actualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bot_cancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel9)
                        .addGap(34, 34, 34)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txt_fecha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_forma_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spin_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bot_actualizar)
                            .addComponent(bot_cancelar)))
                    .addComponent(jLabel5)
                    .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163)
                .addComponent(lbl_id_huesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(384, 384, 384)
                        .addComponent(bot_volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bot_buscar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bot_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bot_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bot_eliminar))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bot_volver)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_buscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(bot_limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bot_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bot_eliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbl_datos.getModel();
        modelo.setRowCount(0);
        mostrar(txt_buscar.getText());
    }//GEN-LAST:event_bot_buscarActionPerformed

    private void txt_fecha_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecha_salidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecha_salidaActionPerformed

    private void cmb_forma_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_forma_pagoActionPerformed
        //DecimalFormat formato = new DecimalFormat("#.##");
        String selectedItem = (String) cmb_forma_pago.getSelectedItem();

        if (selectedItem.equals("Dolar")) {
            int value = (int) spin_num.getValue();
            double result = value * 20;
            txt_total.setText(String.valueOf(result));
        } else if (selectedItem.equals("Euro")) {
            int value = (int) spin_num.getValue();
            double result = value * 20 * 0.93;
            txt_total.setText(String.valueOf(result));
        } else if (selectedItem.equals("libra")) {
            int value = (int) spin_num.getValue();
            double result = value * 20 * 0.81;
            txt_total.setText(String.valueOf(result));
        }else if (selectedItem.equals("Yen")) {
            int value = (int) spin_num.getValue();
            double result = value * 20 * 140.66;
            txt_total.setText(String.valueOf(result));
        }else if (selectedItem.equals("won")) {
            int value = (int) spin_num.getValue();
            double result = value * 20 * 1323.43;
            txt_total.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_cmb_forma_pagoActionPerformed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
   if (txt_fecha_entrada.getText().equals("") || txt_fecha_salida.getText().equalsIgnoreCase("") || txt_valor.getText().equalsIgnoreCase("") || txt_total.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos");
        } else {
            try {
                ps = con.prepareStatement("UPDATE reserva SET fecha_entrada = ?,fecha_salida = ?,valor=?,forma_pago = ?,total = ?  WHERE id_reserva = " + txt_id.getText());
                ps.setString(1, txt_fecha_entrada.getText());
                ps.setString(2, txt_fecha_salida.getText());
                ps.setString(3, txt_valor.getText());
                ps.setString(4, (String) cmb_forma_pago.getSelectedItem());
                ps.setString(5, txt_total.getText());
                int res = ps.executeUpdate();
                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al actualizar");
                }
            } catch (SQLException ex) {
                System.out.println("error: " + ex);
            }
        }
        DefaultTableModel modelo = (DefaultTableModel) tbl_datos.getModel();
        modelo.setRowCount(0);
        mostrar(txt_buscar.getText());
        txt_fecha_entrada.setText("");
        txt_fecha_salida.setText("");
        txt_id.setText("");
        txt_total.setText("");
        txt_valor.setText("");
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void bot_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bot_cancelarActionPerformed

    private void spin_numStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_numStateChanged
        int value = (int) spin_num.getValue();
        int result = value * 20;
        txt_valor.setText(String.valueOf(result));
    }//GEN-LAST:event_spin_numStateChanged

    private void bot_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbl_datos.getModel();
        modelo.setRowCount(0);
    }//GEN-LAST:event_bot_limpiarActionPerformed

    private void bot_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_volverActionPerformed
        dispose();
        principal.getMenu_admin().setEnabled(true);
        principal.getMenu_huesped().setEnabled(false);
    }//GEN-LAST:event_bot_volverActionPerformed

    private void bot_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_eliminarActionPerformed
        int fila = tbl_datos.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tbl_datos.getModel();
        int id;
        id = Integer.parseInt(tbl_datos.getValueAt(fila, 0).toString());
        try {
            ps = con.prepareStatement("DELETE FROM reserva WHERE id_reserva = " + id);
            int elim = ps.executeUpdate();
            if (elim > 0) {
                JOptionPane.showMessageDialog(null, "Dato eliminado");
                modelo.removeRow(fila);
            } else {
                JOptionPane.showMessageDialog(null, "no selecciono ninguna fila");
            }
        } catch (SQLException ex) {
            Logger.getLogger(control_reserva.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bot_eliminarActionPerformed

    private void bot_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_editarActionPerformed
        int fila = tbl_datos.getSelectedRow();
        if (fila >= 0) {
            txt_id.setText(tbl_datos.getValueAt(fila, 0).toString());
            txt_fecha_entrada.setText(tbl_datos.getValueAt(fila, 1).toString());
            txt_fecha_salida.setText(tbl_datos.getValueAt(fila, 2).toString());
            txt_valor.setText(tbl_datos.getValueAt(fila, 3).toString());
            //combo rol
            String mipago = tbl_datos.getValueAt(fila, 4).toString();
            cmb_forma_pago.setSelectedItem(mipago);
            //
            //txt_id_huesped.setText(tbl_datos.getValueAt(fila, 5).toString());
            txt_total.setText(tbl_datos.getValueAt(fila, 6).toString());
            //cambiar spinner valor
            String valorTexto = tbl_datos.getValueAt(fila, 3).toString();
            int lvalor = Integer.parseInt(valorTexto);
            int resultado = (lvalor - 20) / 20 + 1;
            spin_num.setValue(resultado);
            //
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila", "FALLIDO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bot_editarActionPerformed

    public void mostrar(String valor) {
        DefaultTableModel modelo = (DefaultTableModel) tbl_datos.getModel();

        String sql = "";
        if (valor.equals("")) {
            sql = "SELECT id_reserva, fecha_entrada, fecha_salida, valor, forma_pago, id_huesped, total FROM  reserva";
        } else {
            sql = "SELECT id_reserva, fecha_entrada, fecha_salida, valor, forma_pago, id_huesped, total FROM reserva WHERE nom_usuario LIKE '%" + valor + "%'";
        }
        Object[] fila = new Object[7];
        try {
            Statement st = con.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                fila[5] = rs.getString(6);
                fila[6] = rs.getString(7);
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(consulta_huespedes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_actualizar;
    private javax.swing.JButton bot_buscar;
    private javax.swing.JButton bot_cancelar;
    private javax.swing.JButton bot_editar;
    private javax.swing.JButton bot_eliminar;
    private javax.swing.JButton bot_limpiar;
    private javax.swing.JButton bot_volver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_forma_pago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_id_huesped;
    private javax.swing.JSpinner spin_num;
    private javax.swing.JTable tbl_datos;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_fecha_entrada;
    private javax.swing.JTextField txt_fecha_salida;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
