/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.reserva_controlador;
import java.awt.FlowLayout;
import java.text.DecimalFormat;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import modelo.reserva;


/**
 *
 * @author cristian
 */
public class crear_reserva extends javax.swing.JFrame {
    
    reserva_controlador hc =new reserva_controlador();
    reserva nueva_reserva = new reserva();
    private menu principal;
    
    int valorGlobal = login.obtenerVariableGlobal();
    
    public void ComboBoxmoneda() {
        cmb_forma_pago.addItem("Dolar");
        cmb_forma_pago.addItem("Euro");
        cmb_forma_pago.addItem("libra");
        cmb_forma_pago.addItem("Yen");
        cmb_forma_pago.addItem("won");
    }
    /**
     * Creates new form crear_reserva
     */
    public crear_reserva(menu p) {
        initComponents();
        principal=p;
        ComboBoxmoneda();
        spin_num.setModel(new SpinnerNumberModel(1, 1, null, 1)); 
                
        String idhuesped = String.valueOf(valorGlobal);
        System.out.println("Valor global crear_reserva: " + idhuesped);
    }


    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_reservacion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_id_huesped = new javax.swing.JLabel();
        txt_fecha_entrada = new javax.swing.JTextField();
        txt_fecha_salida = new javax.swing.JTextField();
        txt_valor = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        cmb_forma_pago = new javax.swing.JComboBox<>();
        bot_reserva = new javax.swing.JButton();
        bot_cancelar = new javax.swing.JButton();
        spin_num = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_reservacion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_reservacion.setText("RESERVACION");

        jLabel2.setText("Fecha entrada:");

        jLabel3.setText("Fecha Salida:");

        jLabel4.setText("Valor en dolar:");

        jLabel5.setText("Forma de Pago:");

        jLabel6.setText("Total (moneda de tu pais):");

        txt_fecha_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecha_salidaActionPerformed(evt);
            }
        });

        cmb_forma_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_forma_pagoActionPerformed(evt);
            }
        });

        bot_reserva.setText("Reservar");
        bot_reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reservaActionPerformed(evt);
            }
        });

        bot_cancelar.setText("Cancelar");
        bot_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cancelarActionPerformed(evt);
            }
        });

        spin_num.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_numStateChanged(evt);
            }
        });

        jLabel7.setText("dias:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_fecha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_forma_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(lbl_id_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spin_num, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bot_reserva)
                        .addGap(18, 18, 18)
                        .addComponent(bot_cancelar)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(142, 142, 142))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_fecha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spin_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bot_reserva)
                        .addComponent(bot_cancelar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_forma_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(72, 72, 72)
                .addComponent(lbl_id_huesped, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_reservacion)
                .addGap(262, 262, 262))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lbl_reservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reservaActionPerformed

        String fe=txt_fecha_entrada.getText();
        String es=txt_fecha_salida.getText();
        String val=txt_valor.getText();
        String formp=(String)cmb_forma_pago.getSelectedItem();
        String total=txt_total.getText();
        if(fe.equals("") || es.equals("") || val.equals("") || formp.equals("") || total.equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese todos los valores","FALLIDO", JOptionPane.ERROR_MESSAGE);
        }else{
            nueva_reserva.setFecha_entr(txt_fecha_entrada.getText());
            nueva_reserva.setFecha_sal(txt_fecha_salida.getText());
            nueva_reserva.setValor(Integer.parseInt(txt_valor.getText()));
            nueva_reserva.setForma_pag( (String)cmb_forma_pago.getSelectedItem());
            nueva_reserva.setHuesped(valorGlobal);
            nueva_reserva.setTotal(Double.parseDouble(txt_total.getText()));
            hc.insertarReserva(nueva_reserva);
            dispose();
        }
        principal.getMenu_admin().setEnabled(false);
        principal.getMenu_huesped().setEnabled(true);
    }//GEN-LAST:event_bot_reservaActionPerformed

    private void txt_fecha_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecha_salidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecha_salidaActionPerformed

    private void spin_numStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_numStateChanged
            int value = (int) spin_num.getValue();
            int result = value * 20;
            txt_valor.setText(String.valueOf(result));
    }//GEN-LAST:event_spin_numStateChanged

    private void cmb_forma_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_forma_pagoActionPerformed
        //DecimalFormat formato = new DecimalFormat("#.##");
        String selectedItem = (String) cmb_forma_pago.getSelectedItem();

        if (selectedItem.equals("Dolar")) {
            int value = (int) spin_num.getValue();
            double result = value * 20;
            txt_total.setText(String.valueOf(result));
        } else if (selectedItem.equals("Euro")) {
            int value = (int) spin_num.getValue();
            double result = value * 20 * 0.93;
            txt_total.setText(String.valueOf(result));
        } else if (selectedItem.equals("libra")) {
            int value = (int) spin_num.getValue();
            double result = value * 20 * 0.81;
            txt_total.setText(String.valueOf(result));
        }else if (selectedItem.equals("Yen")) {
            int value = (int) spin_num.getValue();
            double result = value * 20 * 140.66;
            txt_total.setText(String.valueOf(result));
        }else if (selectedItem.equals("won")) {
            int value = (int) spin_num.getValue();
            double result = value * 20 * 1323.43;
            txt_total.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_cmb_forma_pagoActionPerformed

    private void bot_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bot_cancelarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cancelar;
    private javax.swing.JButton bot_reserva;
    private javax.swing.JComboBox<String> cmb_forma_pago;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_id_huesped;
    private javax.swing.JLabel lbl_reservacion;
    private javax.swing.JSpinner spin_num;
    private javax.swing.JTextField txt_fecha_entrada;
    private javax.swing.JTextField txt_fecha_salida;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
