/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;

/**
 *
 * @author cristian
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        menu_admin.setEnabled(false);
        menu_huesped.setEnabled(false);

        int valorGlobal = login.obtenerVariableGlobal();

        String idhuesped = String.valueOf(valorGlobal);
        System.out.println("Valor global: " + idhuesped);

        //txt_nuevo.setText(String.valueOf(valorGlobal));
    }

    public JMenu getMenu_admin() {
        return menu_admin;
    }

    public void setMenu_admin(JMenu menu_admin) {
        this.menu_admin = menu_admin;
    }

    public JMenu getMenu_huesped() {
        return menu_huesped;
    }

    public void setMenu_huesped(JMenu menu_huesped) {
        this.menu_huesped = menu_huesped;
    }

    public int obtenerid(int ids) {
        return ids;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_inicio = new javax.swing.JMenu();
        I_menu_ingresar = new javax.swing.JMenuItem();
        I_menu_registro = new javax.swing.JMenuItem();
        I_menu_salir = new javax.swing.JMenuItem();
        menu_huesped = new javax.swing.JMenu();
        I_menu_reserva = new javax.swing.JMenuItem();
        I_menu_misreservas = new javax.swing.JMenuItem();
        menu_admin = new javax.swing.JMenu();
        I_menu_consultaH = new javax.swing.JMenuItem();
        I_menu_consultaR = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        menu_inicio.setText("Inicio");

        I_menu_ingresar.setText("Ingresar");
        I_menu_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_menu_ingresarActionPerformed(evt);
            }
        });
        menu_inicio.add(I_menu_ingresar);

        I_menu_registro.setText("Registrate");
        I_menu_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_menu_registroActionPerformed(evt);
            }
        });
        menu_inicio.add(I_menu_registro);

        I_menu_salir.setText("Salir");
        I_menu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_menu_salirActionPerformed(evt);
            }
        });
        menu_inicio.add(I_menu_salir);

        jMenuBar1.add(menu_inicio);

        menu_huesped.setText("Huesped");

        I_menu_reserva.setText("Reservar");
        I_menu_reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_menu_reservaActionPerformed(evt);
            }
        });
        menu_huesped.add(I_menu_reserva);

        I_menu_misreservas.setText("Mis reservas");
        I_menu_misreservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_menu_misreservasActionPerformed(evt);
            }
        });
        menu_huesped.add(I_menu_misreservas);

        jMenuBar1.add(menu_huesped);

        menu_admin.setText("Administrador");

        I_menu_consultaH.setText("Consulta huespedes");
        I_menu_consultaH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_menu_consultaHActionPerformed(evt);
            }
        });
        menu_admin.add(I_menu_consultaH);

        I_menu_consultaR.setText("Consulta Reservaciones");
        I_menu_consultaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_menu_consultaRActionPerformed(evt);
            }
        });
        menu_admin.add(I_menu_consultaR);

        jMenuBar1.add(menu_admin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void I_menu_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_menu_ingresarActionPerformed
        login l = new login(this);
        l.setVisible(true);
    }//GEN-LAST:event_I_menu_ingresarActionPerformed

    private void I_menu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_menu_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_I_menu_salirActionPerformed

    private void I_menu_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_menu_registroActionPerformed
        crear_huesped ch = new crear_huesped(this);
        ch.setVisible(true);
    }//GEN-LAST:event_I_menu_registroActionPerformed

    private void I_menu_reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_menu_reservaActionPerformed
        crear_reserva cr = new crear_reserva(this);
        cr.setVisible(true);
    }//GEN-LAST:event_I_menu_reservaActionPerformed

    private void I_menu_consultaHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_menu_consultaHActionPerformed
        control_huesped ch = new control_huesped(this);
        ch.setVisible(true);
    }//GEN-LAST:event_I_menu_consultaHActionPerformed

    private void I_menu_consultaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_menu_consultaRActionPerformed
        control_reserva cr = new control_reserva(this);
        cr.setVisible(true);
    }//GEN-LAST:event_I_menu_consultaRActionPerformed

    private void I_menu_misreservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_menu_misreservasActionPerformed
        consulta_huespedes hues = new consulta_huespedes(this);
        hues.setVisible(true);
    }//GEN-LAST:event_I_menu_misreservasActionPerformed

    private void showJInternalFrameCenterPosition(JInternalFrame jInternalFrame) {
        Panel.add(jInternalFrame);
        Dimension componentDim = jInternalFrame.getSize();
        Dimension desktopDim = Panel.getSize();
        int width = (int) (desktopDim.getWidth() - componentDim.getWidth()) / 2;
        int heigth = (int) (desktopDim.getHeight() - componentDim.getHeight()) / 2;
        Dimension positionDim = new Dimension(width, heigth);
        jInternalFrame.setBounds((int) positionDim.getWidth(), (int) positionDim.getHeight(), jInternalFrame.getWidth(), jInternalFrame.getHeight());
        jInternalFrame.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem I_menu_consultaH;
    private javax.swing.JMenuItem I_menu_consultaR;
    private javax.swing.JMenuItem I_menu_ingresar;
    private javax.swing.JMenuItem I_menu_misreservas;
    private javax.swing.JMenuItem I_menu_registro;
    private javax.swing.JMenuItem I_menu_reserva;
    private javax.swing.JMenuItem I_menu_salir;
    private javax.swing.JPanel Panel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_admin;
    private javax.swing.JMenu menu_huesped;
    private javax.swing.JMenu menu_inicio;
    // End of variables declaration//GEN-END:variables

}
